version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "cypress.prod.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "cypress.prod.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - run: $(yarn bin)/cypress run --env configFile=prod
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
            fingerprints:
              - "47:c4:fa:aa:64:b7:a0:2f:ba:5a:1f:52:e2:c1:db:ec"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -v -p 6543 $SSH_USER@$SSH_HOST "scp -rp mihail-gaberov.eu/* $SSH_USER@$SSH_HOST:/public_html/"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
